#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration,
displays Best School and  Hi on a new line.

index=0

while [ $index -lt 10 ]
do
  if [ $index -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( index++ ))
done
