#!/usr/bin/env bash
# This script The content of the current directory in a list format
#   displays only the part of the name after the first dash.

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '_' -f2
done
